### ISSUE TITLE
Create a reusable Github action

### ISSUE THREAD

**Issue by turion** [Kleidukos/get-tested#22]
It would be cool if there was a Github action that one could simply use like:

```yaml
jobs:
  get-tested:
    name: Generate matrix
    steps:
    -uses: Kleidukos/get-tested/v1

  build:
    needs: get-tested
    strategy:
      matrix: ${{ fromJSON(needs.get-tested.outputs.matrix) }}
...
```

That way, one saves on code to write, and dependabot could automatically bump versions.
