### ISSUE TITLE
Provide more information in the build matrix

### ISSUE THREAD

**Issue by mmhat** [Kleidukos/get-tested#52]
In https://github.com/Kleidukos/print-api/pull/16#discussion_r1739917913 and in https://github.com/Kleidukos/print-api/issues/24#issuecomment-2323607876 I expressed the need for more information in the build matrix generated by `get-tested`.
For example, given a stanza
```cabal
tested-with: GHC ==8.10.7 || ==9.2.8 || ==9.10.1
```
I think it was nice if `get-tested` indicates what the oldest and the newest GHC version in the `tested-with` field is.
The build matrix I envision could be something like:
```yaml
matrix:
  include:
  - ghc: 8.10.7
    oldest: true
    newest: false
  - ghc: 9.2.8
    oldest: false
    newest: false
  - ghc: 9.10.1
    oldest: false
    newest: true
```
With those additional fields at hand it would be possible to run some jobs/steps only for the oldest or the newest version respectively.

Also, it was nice if get tested had options like `--oldest-only` (`oldest-only: <true|false>` in the GH action) and `--newest-only`  (`newest-only: <true|false>` in the GH action) to generate a matrix containing only the oldest or newest version.

A potential usecase is https://github.com/Kleidukos/print-api/issues/24.
